### ISSUE TITLE
possible for a name change?

### ISSUE THREAD

**Issue by colindickson** [marcwebbie/passpie#25]
This library is great and i intend to use it forever.   However, i'm afraid that with a name that looks to english-speaking people as "piss words", this will not really get off the ground.   Many great python libraries don't have "py" in their names.   Its not a requirement, or even a convention.

**Comment by marcwebbie** [comment]
Hello @colindickson 

Yes, I've been thinking about a name change. English is not my first language so I didn't realise it might sound bad in other languages, for the moment it is complicated because of the structure of a pyssword database. But I am trying some ideas, if it works right I will change the name.

Thank you for your contribution

**Comment by marcwebbie** [comment]
Done, package now is called passpie
