### ISSUE TITLE
passpie init hangs

### ISSUE THREAD

**Issue by ianjuma** [marcwebbie/passpie#51]
passport init hangs, can't initialize a database.
```bash
app:git:(master) ✗ passpie init
Passphrase: 
Repeat for confirmation: 

```
running on the latest pip version
```python
Requirement already satisfied (use --upgrade to upgrade): passpie in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): tabulate==0.7.5 in /usr/local/lib/python2.7/dist-packages (from passpie)
Requirement already satisfied (use --upgrade to upgrade): click==4.0 in /usr/local/lib/python2.7/dist-packages (from passpie)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in /usr/local/lib/python2.7/dist-packages (from passpie)
Requirement already satisfied (use --upgrade to upgrade): tinydb==2.3.2 in /usr/local/lib/python2.7/dist-packages (from passpie)
Requirement already satisfied (use --upgrade to upgrade): gnupg==2.0.2 in /usr/local/lib/python2.7/dist-packages (from passpie)
Requirement already satisfied (use --upgrade to upgrade): psutil>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from gnupg==2.0.2->passpie)
```

**Comment by marcwebbie** [comment]
It takes a while to generate gpg keys on some environments. Which operating system are you using?

**Comment by ianjuma** [comment]
ubuntu 12.04, it takes a very long time, painfully slow. Anything that could be done to speed it up?

**Comment by marcwebbie** [comment]
Hello @ianjuma 

Yes sometimes it takes a long time because of [entropy](http://en.wikipedia.org/wiki/Address_space_layout_randomization) on the host machine. It was taking me a long time as well on an ubuntu server(even more if it is a virtual machine), I managed to generate more entropy after installing `haveged`

```
sudo apt-get install haveged
```

You could also try this solution right here: http://serverfault.com/questions/214605/gpg-not-enough-entropy

Thanks,

**Comment by ianjuma** [comment]
oh: that'll help. Maybe have that in the docs as well. Thanks.
