### ISSUE TITLE
[Feature Request/Question]

### ISSUE THREAD

**Issue by mekhami** [marcwebbie/passpie#67]
Is it not possible to have your email be your login name? Given the fullname structure uses the @, you can't likely do myemail@gmail.com@thatsiteiuse for the name of the entry.

Or can you, and I'm just missing something?

**Comment by tundramonkey** [comment]
@mekhami I'll leap in here since this is what I'm doing you can easily put things like `firstname.lastname@mymail.com@thatsiteiuse` and get what you're going for. That will also work if you want groupings (I know I just moved over to passpie last night and one of the first things I checked.
`firstname.lastname@mymail.com@workstuff/thatsiteiuse`.

Even then if you don't put it in via the `passpie add firstname.lastname@mymail.com@thatsiteiuse` you can use the `passpie update thatsiteiuse` and go  back and fix anything you've already put in.

**Comment by marcwebbie** [comment]
@mekhami good question, that makes me think that `fullname` syntax might not be as document as it should. As @tundramonkey has mentioned, you can have `user@gmail.com@example.com` and also make queries using only the name: `example.com` as soon as that is the credential named `example.com`

I will let this issue open so others can take a look.

**Comment by marcwebbie** [comment]
I will be closing this issue for now.

For those of you having the same difficulty understand fullname syntax: https://github.com/marcwebbie/passpie/blob/master/docs/fullname.md
